from karaoke.core.song import Song
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from karaoke.cli import LOCAL_DB

songs = [
    ("You'll Be Back", "Hamilton", "NeyIh_uFilY"),
    ("Wait for it", "Hamilton", "offb3D_Br_0"),
    ("My Shot", "Hamilton", "_vr5w9PefnM"),
    ("מפחד עלייך", "מירי מסיקה ואיזי", "5zdoMMe34M8"),
    ("פנתרה", "נועה קירל", "HG3-AWLV8ug"),
    ("מי זאת", "אנה זק", "ihhtn8boMBQ"),
    ("ליבינג דה דרים", "נונו", "xvqfVpmj27g"),
    ("קיוט בוי", "נונו", "_z-AQBdjFC8"),
    ("הולכת איתך", "נרקיס", "xUJZ8ZtGsF0"),
    ("מרלין מונרו", "שייגעצ", "lFgV13sgBk4"),
    ("אבא עורך דין", "שייגעצ", "wrxJWIdi0I4"),
    ("Unstoppable", "Sia", "Os1yZi0DM4c"),
    ("7 Rings", "Ariana Grande", "7BfhCUB_YkI"),
    (
        "The Middle",
        "Jimmy Eat World",
        "nWj94J8f4k8",
    ),
    ("Levitating", "Dua Lipa", "nK9hD9_SAdU"),
    ("abcdefu", "GAYLE", "25riE6PyRlo"),
    (
        "Peaches",
        "Justin Bieber ft. Daniel Caesar & Giveon",
        "9b3_RAobRr8",
    ),
    (
        "Yellow",
        "Coldplay",
        "1Fv5IVf9KAc",
    ),
    (
        "Fix You",
        "Coldplay",
        "ME2nvqrzz34",
    ),
    (
        "Toxicity",
        "System Of A Down",
        "TXenLQdECkM",
    ),
    ("Right Hand Man", "Hamilton", "Yj_QOj1wHrQ"),
    (
        "Non-Stop",
        "Hamilton",
        "jbcl5TOwb4g",
    ),
    (
        "The Room Where It Happens",
        "Hamilton",
        "s3zKr6bt1ec",
    ),
    (
        "Ten Duel Commandments + Meet Me Inside",
        "Hamilton",
        "hI7-BCYjrGE",
    ),
    (
        "Dear Theodosia",
        "Hamilton",
        "O3Wk9ATpUp4",
    ),
    ("Right Now", "SR-71", "o8gKzX9iZKU"),
    ("It's Quiet Uptown", "Hamilton", "HzLR36oKMcU"),
    (
        "Say No To This",
        "Hamilton",
        "5c6400EBQLI",
    ),
    (
        "Cabinet Battle #1",
        "Hamilton",
        "w_7Ihjw997U",
    ),
    ("The World was wide enough", "Hamilton", "q2N5Tz-LToQ"),
    (
        "Blow Us All Away + Stay Alive (Reprise)",
        "Hamilton",
        "f1EawurJFmI",
    ),
    ("Satisfied", "Hamilton", "BJUh4PuMYQk"),
    ("Code Monkey", "Jonathan Coulton", "BvwTKkQZRJ8"),
    (
        "Tom Cruise Crazy",
        "Jonathan Coulton",
        "zOx0WrpZVCM",
    ),
    (
        "Here It Goes Again",
        "OK Go",
        "ykhrjWJA-UQ",
    ),
    ("This Too Shall Pass", "OK Go", "IyO6yzUT-Qo"),
    (
        "Breezy Slide",
        "Brian David Gilbert & Louie Zong",
        "9geqpIM-0y8",
    ),
    ("Thank You God", "Tim Minchin", "cO6OPNiM-IQ"),
    ("You Grew on me", "Tim Minchin", "JxNeY8sqMpc"),
    ("If I Didn't Have You", "Tim Minchin", "S4W1u44hsT4"),
    ("The Good Book", "Tim Minchin", "4jL_G9Ky0NY"),
    ("If you really loved me", "Tim Minchin", "XpR1wp8v-nY"),
    ("Welcome To The Internet", "Bo Burnham", "FK0vZWztu80"),
    ("God's Plan", "Drake", "b1xiezhCNJo"),
    ("Passionfruit", "Drake", "XYxt7P6Embw"),
    ("Save Your Tears", "The Weeknd", "n4dG93qt0B8"),
    ("Blinding Lights", "The Weeknd", "Cj4hcXZs3Lc"),
    ("One Dance", "Drake ft. Wizkid & Kyla", "HoKBVMIi2IY"),
    ("Nice For What", "Drake", "JF4Z5GWZNyg"),
    (
        "Hold On, We're Going Home",
        "Drake and Majid Jordan",
        "mdizaRgRTXQ",
    ),
    (
        "Starboy",
        "Weeknd Feat. Daft Punk",
        "hZVk4fnnkso",
    ),
    (
        "Started From The Bottom",
        "Drake",
        "OO_FIN8xzgM",
    ),
    (
        "Formation",
        "Beyoncé",
        "N66it_Me25k",
    ),
    ("1985", "Bowling for Soup", "oFIApdolE6M"),
    ("I Want It That Way", "Backstreet Boys", "NxilU56kPu0"),
    ("Motherlover", "The Lonely Island", "SeoZ8Us_Frg"),
    (
        "Boulevard Of Broken Dreams",
        "Green Day",
        "r8BdFXaYE8s",
    ),
    ("Holiday", "Green Day", "azA7YCqiiZU"),
    ("יש בי אהבה", "נועה קירל", "0qbONOLEgH8"),
    ("חנניה", "חנן בן ארי", "tv9aFV1AwDU"),
    ("Miss You", "Oliver Tree, Robin Schulz", "h6HX9kqEj2k"),
    ("שגר פגר", "הבילויים", "XPR-CGu1T6s"),
    (
        "Unicorn",
        "Noa Kirel",
        "pb2DDn4qL9c",
    ),
    ("Rockstar", "Post Malone ft. 21 Savage", "TP7JVS4YPpA"),
    ("Circles", "Post Malone", "hlk6z9nJxGg"),
    ("Wow", "Post Malone", "lz6ctTNbeMc"),
    ("Better Now", "Post Malone", "3Fzt8znweY4"),
    ("Cha Cha Cha", "Käärijä", "nsj5ssrzbTQ"),
    ("What'd I Miss", "Hamilton", "iaVYORLWeQE"),
    (
        "Washington On Your Side",
        "Hamilton",
        "KoSZ3x9JLWE",
    ),
    ("The Election Of 1800", "Hamilton", "zY8nbKX5a2s"),
    ("Cabinet battle #2", "Hamilton", "_ibSc-sW0VE"),
    ("Aaron Burr, sir", "Hamilton", "cLgo9drgZ6g"),
    ("Stan", "Eminem feat. Dido", "N6J3renv2qQ"),
    ("Grace Kelly", "MIKA", "ib_PhEzRqTw"),
    ("גשם חזק", "מוניקס סקס", "GXVubCH5Um0"),
    ("Me and The Sky", "Come From Away", "3dx7KdN_9X0"),
    ("White Iverson", "Post Malone", "vZgua0TE9aQ"),
    ("Flowers", "Miley Cyrus", "fO4wsNsXtDg"),
    ("תיק קטן", "נס & סטילה", "gHZwlGCQ9a0"),
    (
        "Only Girl (In The World)",
        "Rihanna Karaoke",
        "M1nv2cvhQJk",
    ),
    (
        "If I Were A Boy",
        "Beyoncé",
        "e3pWWSNkwEs",
    ),
    (
        "Love Me Like You Do",
        "Ellie Goulding",
        "tW8A67aySrs",
    ),
    (
        "thank u, next",
        "Ariana Grande",
        "v54fN3RLE18",
    ),
    (
        "God is a woman",
        "Ariana Grande",
        "dnB3Nw3NQ40",
    ),
    (
        "Don't Let Me Down",
        "The Chainsmokers",
        "Sb3dbE_vqhc",
    ),
    (
        "Clean Bandit",
        "Rockabye ft. Sean Paul & Anne-Marie",
        "jOIT1JZ2S-k",
    ),
    ("Halo", "Beyoncé", "Pj7KDeGkhH0"),
    (
        "Treat You Better",
        "Shawn Mendes",
        "FrN_2Mj-u8Q",
    ),
    (
        "Unholy",
        "Sam Smith, Kim Petras",
        "CNQecEnK26s",
    ),
    ("Shake It Off", "Taylor Swift", "KJQ8Gv1HXnw"),
    (
        "Wrecking Ball",
        "Miley Cyrus",
        "c8tEmyLEUXc",
    ),
    ("Firework", "Katy Perry", "ivV0yZwTLac"),
    (
        "Rude Boy",
        "Rihanna",
        "LfACscj0NyE",
    ),
    (
        "Love On Top",
        "Beyoncé",
        "G1vNG0HmtTY",
    ),
    (
        "A Thousand Years",
        "Christina Perry",
        "AWehaFFYbO8",
    ),
    (
        "We Don't Talk Anymore",
        "Charlie Puth",
        "9Zv5ZlRMHIo",
    ),
    (
        "New Rules",
        "Dua Lipa",
        "ELzVcOw6aGA",
    ),
    (
        "Cheap Thrills",
        "Sia",
        "HiuDdQeUyUc",
    ),
    ("Numb", "Linkin Park", "9glHyVEnJAE"),
    ("Loreen", "Tattoo", "b9skN7auv4c"),
    ("Shawn Mendes", "Stitches", "55TwvRv_Xog"),
    (
        "Somebody That I Used To Know",
        "Gotye and Kimbra",
        "toHUpXZRgTQ",
    ),
    (
        "Aerials",
        "System Of A Down",
        "kfsWXM3Yit8",
    ),
    (
        "Sweet Child o' Mine",
        "Guns N' Roses",
        "uhiamj_I7II",
    ),
    ("Bring Me To Life", "Evanescence", "frpfRwGv6KU"),
    ("Going Under", "Evanescence", "hmgPwlcQHHg"),
    ("My Immortal", "Evanescence", "Dv4s4KFptCE"),
    ("Feel Good Inc.", "Gorillaz", "VbkUuIXXyb4"),
    ("How You Remind Me", "Nickelback", "J_FhZ-n3B5M"),
    ("You Oughta Know", "Alanis Morisette", "BBdPnDnmPzc"),
    ("Born This Way", "Lady Gaga", "NatvhO5ihAk"),
    ("Nobody's Wife", "Anouk", "yqQJgtdBnvM"),
    (
        "Ship To Wreck",
        "Florence + the Machine",
        "cWwp6GZBZkU",
    ),
    ("The Chain", "Fleetwood Mac", "Kc6dEtZk8hM"),
    (
        "Think About Things",
        "Daði Freyr (Daði & Gagnamagnið)",
        "paLqOMmRqG0",
    ),
    ("A Thousand Miles", "Vanessa Carlton", "u2K-525UPUA"),
    ("Shut Up And Dance", "Walk the Moon", "71qqtDWFVl4"),
    ("Cake By The Ocean", "DNCE", "dWm4HGEf2u0"),
    (
        "Somebody to Love",
        "Jefferson Airplane",
        "X0jcTY5lp0M",
    ),
    ("High Hopes", "Panic! At The Disco", "Dc7L5ZzlrCc"),
    ("Bad Guy", "Billie Eilish", "GsFlbMS7UIc"),
    (
        "Rolling in The Deep",
        "Adele",
        "B3O1OlTWXSA",
    ),
    (
        "Hello",
        "Adele",
        "doWWkG2gPPE",
    ),
    (
        "Take Me Home, Country Roads",
        "John Denver",
        "7aNW9hRKYA8",
    ),
    (
        "I Don't Want To Miss A Thing",
        "Aerosmith",
        "s9Qc54Jp-6M",
    ),
    ("Africa", "Toto", "CRrZlEF7-SU"),
    ("Survivor", "Eye Of The Tiger", "83ZFZPhxskc"),
    ("All Star", "Smash Mouth", "ABOYo7ioQJo"),
    ("Livin' La Vida Loca", "Ricky Martin", "tOAs-c5jiuQ"),
    (
        "Come & Go",
        "Juice WRLD & Marshmello",
        "8_cK73sMi4g",
    ),
    ("Latchkey Cats", "Unknown", "7rCPM_IZOTk"),
    (
        "Californication",
        "Red Hot Chili Peppers",
        "EFI1qU1TP5o",
    ),
    ("Baby", "Justin Bieber ft. Ludacris", "1a5SWpp9Wfg"),
    ("Dancing On My Own", "Calum Scott", "DvEXv4Shx7s"),
    ("Love is an open door", "Unknown", "IWw-LQ2qM3c"),
]


def main():
    engine = create_engine(LOCAL_DB, echo=True)
    with sessionmaker(bind=engine)() as session:
        for songtup in songs:
            song = Song(
                title=songtup[0],
                artist=songtup[1],
                video_link=f"https://www.youtube.com/embed/{songtup[2]}",
            )
            session.add(song)
        session.commit()


if __name__ == "__main__":
    main()
