kr song create --title "You'll Be Back" --artist "Hamilton" --video-link "NeyIh_uFilY"
kr song create --title "Wait for it" --artist "Hamilton" --video-link "offb3D_Br_0"
kr song create --title "My Shot" --artist "Hamilton" --video-link "_vr5w9PefnM"
kr song create --title "מפחד עלייך" --artist "מירי מסיקה ואיזי" --video-link "5zdoMMe34M8"
kr song create --title "פנתרה" --artist "נועה קירל" --video-link "HG3-AWLV8ug"
kr song create --title "מי זאת" --artist "אנה זק" --video-link "ihhtn8boMBQ"
kr song create --title "ליבינג דה דרים" --artist "נונו" --video-link "xvqfVpmj27g"
kr song create --title "קיוט בוי" --artist "נונו" --video-link "_z-AQBdjFC8"
kr song create --title "הולכת איתך" --artist "נרקיס" --video-link "xUJZ8ZtGsF0"
kr song create --title "מרלין מונרו" --artist "שייגעצ" --video-link "lFgV13sgBk4"
kr song create --title "אבא עורך דין" --artist "שייגעצ" --video-link "wrxJWIdi0I4"
kr song create --title "Unstoppable" --artist "Sia" --video-link "Os1yZi0DM4c"
kr song create --title "7 Rings" --artist "Ariana Grande" --video-link "7BfhCUB_YkI"
kr song create --title "The Middle" --artist "Jimmy Eat World" --video-link "nWj94J8f4k8"
kr song create --title "Levitating" --artist "Dua Lipa" --video-link "nK9hD9_SAdU"
kr song create --title "abcdefu" --artist "GAYLE" --video-link "25riE6PyRlo"
kr song create --title "Peaches" --artist "Justin Bieber ft. Daniel Caesar & Giveon" --video-link "9b3_RAobRr8"
kr song create --title "Yellow" --artist "Coldplay" --video-link "1Fv5IVf9KAc"
kr song create --title "Fix You" --artist "Coldplay" --video-link "ME2nvqrzz34"
kr song create --title "Toxicity" --artist "System Of A Down" --video-link "TXenLQdECkM"
kr song create --title "Right Hand Man" --artist "Hamilton" --video-link "Yj_QOj1wHrQ"
kr song create --title "Non-Stop" --artist "Hamilton" --video-link "jbcl5TOwb4g"
kr song create --title "The Room Where It Happens" --artist "Hamilton" --video-link "s3zKr6bt1ec"
kr song create --title "Ten Duel Commandments + Meet Me Inside" --artist "Hamilton" --video-link "hI7-BCYjrGE"
kr song create --title "Dear Theodosia" --artist "Hamilton" --video-link "O3Wk9ATpUp4"
kr song create --title "Right Now" --artist "SR-71" --video-link "o8gKzX9iZKU"
kr song create --title "It's Quiet Uptown" --artist "Hamilton" --video-link "HzLR36oKMcU"
kr song create --title "Say No To This" --artist "Hamilton" --video-link "5c6400EBQLI"
kr song create --title "Cabinet Battle #1" --artist "Hamilton" --video-link "w_7Ihjw997U"
kr song create --title "The World was wide enough" --artist "Hamilton" --video-link "q2N5Tz-LToQ"
kr song create --title "Blow Us All Away + Stay Alive (Reprise)" --artist "Hamilton" --video-link "f1EawurJFmI"
kr song create --title "Satisfied" --artist "Hamilton" --video-link "BJUh4PuMYQk"
kr song create --title "Code Monkey" --artist "Jonathan Coulton" --video-link "BvwTKkQZRJ8"
kr song create --title "Tom Cruise Crazy" --artist "Jonathan Coulton" --video-link "zOx0WrpZVCM"
kr song create --title "Here It Goes Again" --artist "OK Go" --video-link "ykhrjWJA-UQ"
kr song create --title "This Too Shall Pass" --artist "OK Go" --video-link "IyO6yzUT-Qo"
kr song create --title "Breezy Slide" --artist "Brian David Gilbert & Louie Zong" --video-link "9geqpIM-0y8"
kr song create --title "Thank You God" --artist "Tim Minchin" --video-link "cO6OPNiM-IQ"
kr song create --title "You Grew on me" --artist "Tim Minchin" --video-link "JxNeY8sqMpc"
kr song create --title "If I Didn't Have You" --artist "Tim Minchin" --video-link "S4W1u44hsT4"
kr song create --title "The Good Book" --artist "Tim Minchin" --video-link "4jL_G9Ky0NY"
kr song create --title "If you really loved me" --artist "Tim Minchin" --video-link "XpR1wp8v-nY"
kr song create --title "Welcome To The Internet" --artist "Bo Burnham" --video-link "FK0vZWztu80"
kr song create --title "God's Plan" --artist "Drake" --video-link "b1xiezhCNJo"
kr song create --title "Passionfruit" --artist "Drake" --video-link "XYxt7P6Embw"
kr song create --title "Save Your Tears" --artist "The Weeknd" --video-link "n4dG93qt0B8"
kr song create --title "Blinding Lights" --artist "The Weeknd" --video-link "Cj4hcXZs3Lc"
kr song create --title "One Dance" --artist "Drake ft. Wizkid & Kyla" --video-link "HoKBVMIi2IY"
kr song create --title "Nice For What" --artist "Drake" --video-link "JF4Z5GWZNyg"
kr song create --title "Hold On, We're Going Home" --artist "Drake and Majid Jordan" --video-link "mdizaRgRTXQ"
kr song create --title "Starboy" --artist "Weeknd Feat. Daft Punk" --video-link "hZVk4fnnkso"
kr song create --title "Started From The Bottom" --artist "Drake" --video-link "OO_FIN8xzgM"
kr song create --title "Formation" --artist "Beyoncé" --video-link "N66it_Me25k"
kr song create --title "1985" --artist "Bowling for Soup" --video-link "oFIApdolE6M"
kr song create --title "I Want It That Way" --artist "Backstreet Boys" --video-link "NxilU56kPu0"
kr song create --title "Motherlover" --artist "The Lonely Island" --video-link "SeoZ8Us_Frg"
kr song create --title "Boulevard Of Broken Dreams" --artist "Green Day" --video-link "r8BdFXaYE8s"
kr song create --title "Holiday" --artist "Green Day" --video-link "azA7YCqiiZU"
kr song create --title "יש בי אהבה" --artist "נועה קירל" --video-link "0qbONOLEgH8"
kr song create --title "חנניה" --artist "חנן בן ארי" --video-link "tv9aFV1AwDU"
kr song create --title "Miss You" --artist "Oliver Tree, Robin Schulz" --video-link "h6HX9kqEj2k"
kr song create --title "שגר פגר" --artist "הבילויים" --video-link "XPR-CGu1T6s"
kr song create --title "Unicorn" --artist "Noa Kirel" --video-link "pb2DDn4qL9c"
kr song create --title "Rockstar" --artist "Post Malone ft. 21 Savage" --video-link "TP7JVS4YPpA"
kr song create --title "Circles" --artist "Post Malone" --video-link "hlk6z9nJxGg"
kr song create --title "Wow" --artist "Post Malone" --video-link "lz6ctTNbeMc"
kr song create --title "Better Now" --artist "Post Malone" --video-link "3Fzt8znweY4"
kr song create --title "Cha Cha Cha" --artist "Käärijä" --video-link "nsj5ssrzbTQ"
kr song create --title "What'd I Miss" --artist "Hamilton" --video-link "iaVYORLWeQE"
kr song create --title "Washington On Your Side" --artist "Hamilton" --video-link "KoSZ3x9JLWE"
kr song create --title "The Election Of 1800" --artist "Hamilton" --video-link "zY8nbKX5a2s"
kr song create --title "Cabinet battle #2" --artist "Hamilton" --video-link "_ibSc-sW0VE"
kr song create --title "Aaron Burr, sir" --artist "Hamilton" --video-link "cLgo9drgZ6g"
kr song create --title "Stan" --artist "Eminem feat. Dido" --video-link "N6J3renv2qQ"
kr song create --title "Grace Kelly" --artist "MIKA" --video-link "ib_PhEzRqTw"
kr song create --title "גשם חזק" --artist "מוניקס סקס" --video-link "GXVubCH5Um0"
kr song create --title "Me and The Sky" --artist "Come From Away" --video-link "3dx7KdN_9X0"
kr song create --title "White Iverson" --artist "Post Malone" --video-link "vZgua0TE9aQ"
kr song create --title "Flowers" --artist "Miley Cyrus" --video-link "fO4wsNsXtDg"
kr song create --title "תיק קטן" --artist "נס & סטילה" --video-link "gHZwlGCQ9a0"
kr song create --title "Only Girl (In The World)" --artist "Rihanna Karaoke" --video-link "M1nv2cvhQJk"
kr song create --title "If I Were A Boy" --artist "Beyoncé" --video-link "e3pWWSNkwEs"
kr song create --title "Love Me Like You Do" --artist "Ellie Goulding" --video-link "tW8A67aySrs"
kr song create --title "thank u, next" --artist "Ariana Grande" --video-link "v54fN3RLE18"
kr song create --title "God is a woman" --artist "Ariana Grande" --video-link "dnB3Nw3NQ40"
kr song create --title "Don't Let Me Down" --artist "The Chainsmokers" --video-link "Sb3dbE_vqhc"
kr song create --title "Clean Bandit" --artist "Rockabye ft. Sean Paul & Anne-Marie" --video-link "jOIT1JZ2S-k"
kr song create --title "Halo" --artist "Beyoncé" --video-link "Pj7KDeGkhH0"
kr song create --title "Treat You Better" --artist "Shawn Mendes" --video-link "FrN_2Mj-u8Q"
kr song create --title "Unholy" --artist "Sam Smith, Kim Petras" --video-link "CNQecEnK26s"
kr song create --title "Shake It Off" --artist "Taylor Swift" --video-link "KJQ8Gv1HXnw"
kr song create --title "Wrecking Ball" --artist "Miley Cyrus" --video-link "c8tEmyLEUXc"
kr song create --title "Firework" --artist "Katy Perry" --video-link "ivV0yZwTLac"
kr song create --title "Rude Boy" --artist "Rihanna" --video-link "LfACscj0NyE"
kr song create --title "Love On Top" --artist "Beyoncé" --video-link "G1vNG0HmtTY"
kr song create --title "A Thousand Years" --artist "Christina Perry" --video-link "AWehaFFYbO8"
kr song create --title "We Don't Talk Anymore" --artist "Charlie Puth" --video-link "9Zv5ZlRMHIo"
kr song create --title "New Rules" --artist "Dua Lipa" --video-link "ELzVcOw6aGA"
kr song create --title "Cheap Thrills" --artist "Sia" --video-link "HiuDdQeUyUc"
kr song create --title "Numb" --artist "Linkin Park" --video-link "9glHyVEnJAE"
kr song create --title "Loreen" --artist "Tattoo" --video-link "b9skN7auv4c"
kr song create --title "Shawn Mendes" --artist "Stitches" --video-link "55TwvRv_Xog"
kr song create --title "Somebody That I Used To Know" --artist "Gotye and Kimbra" --video-link "toHUpXZRgTQ"
kr song create --title "Aerials" --artist "System Of A Down" --video-link "kfsWXM3Yit8"
kr song create --title "Sweet Child o' Mine" --artist "Guns N' Roses" --video-link "uhiamj_I7II"
kr song create --title "Bring Me To Life" --artist "Evanescence" --video-link "frpfRwGv6KU"
kr song create --title "Going Under" --artist "Evanescence" --video-link "hmgPwlcQHHg"
kr song create --title "My Immortal" --artist "Evanescence" --video-link "Dv4s4KFptCE"
kr song create --title "Feel Good Inc." --artist "Gorillaz" --video-link "VbkUuIXXyb4"
kr song create --title "How You Remind Me" --artist "Nickelback" --video-link "J_FhZ-n3B5M"
kr song create --title "You Oughta Know" --artist "Alanis Morisette" --video-link "BBdPnDnmPzc"
kr song create --title "Born This Way" --artist "Lady Gaga" --video-link "NatvhO5ihAk"
kr song create --title "Nobody's Wife" --artist "Anouk" --video-link "yqQJgtdBnvM"
kr song create --title "Ship To Wreck" --artist "Florence + the Machine" --video-link "cWwp6GZBZkU"
kr song create --title "The Chain" --artist "Fleetwood Mac" --video-link "Kc6dEtZk8hM"
kr song create --title "Think About Things" --artist "Daði Freyr (Daði & Gagnamagnið)" --video-link "paLqOMmRqG0"
kr song create --title "A Thousand Miles" --artist "Vanessa Carlton" --video-link "u2K-525UPUA"
kr song create --title "Shut Up And Dance" --artist "Walk the Moon" --video-link "71qqtDWFVl4"
kr song create --title "Cake By The Ocean" --artist "DNCE" --video-link "dWm4HGEf2u0"
kr song create --title "Somebody to Love" --artist "Jefferson Airplane" --video-link "X0jcTY5lp0M"
kr song create --title "High Hopes" --artist "Panic! At The Disco" --video-link "Dc7L5ZzlrCc"
kr song create --title "Bad Guy" --artist "Billie Eilish" --video-link "GsFlbMS7UIc"
kr song create --title "Rolling in The Deep" --artist "Adele" --video-link "B3O1OlTWXSA"
kr song create --title "Hello" --artist "Adele" --video-link "doWWkG2gPPE"
kr song create --title "Take Me Home, Country Roads" --artist "John Denver" --video-link "7aNW9hRKYA8"
kr song create --title "I Don't Want To Miss A Thing" --artist "Aerosmith" --video-link "s9Qc54Jp-6M"
kr song create --title "Africa" --artist "Toto" --video-link "CRrZlEF7-SU"
kr song create --title "Survivor" --artist "Eye Of The Tiger" --video-link "83ZFZPhxskc"
kr song create --title "All Star" --artist "Smash Mouth" --video-link "ABOYo7ioQJo"
kr song create --title "Livin' La Vida Loca" --artist "Ricky Martin" --video-link "tOAs-c5jiuQ"
kr song create --title "Come & Go" --artist "Juice WRLD & Marshmello" --video-link "8_cK73sMi4g"
kr song create --title "Latchkey Cats" --artist "Unknown" --video-link "7rCPM_IZOTk"
kr song create --title "Californication" --artist "Red Hot Chili Peppers" --video-link "EFI1qU1TP5o"
kr song create --title "Baby" --artist "Justin Bieber ft. Ludacris" --video-link "1a5SWpp9Wfg"
kr song create --title "Dancing On My Own" --artist "Calum Scott" --video-link "DvEXv4Shx7s"
kr song create --title "Love is an open door" --artist "Unknown" --video-link "IWw-LQ2qM3c"
